test:
  name: ceadar
  description:
    This is an example benchmark for caliper, to test marbles through containerization
  workers:
    type: local
    number: 2
  rounds:
  - label: init
    description: Creating the marbles
    txNumber: 300
    rateControl:
      type: fixed-rate
      opts:
        tps: 50
    callback: cal-config/init.js
  - label: query
    description: Querying the marbles
    txDuration: 30
    rateControl:
      type: fixed-rate
      opts:
        tps: 10
    callback: cal-config/query.js
monitor:
  type:
    - docker
  docker:
    name:
      - all
  interval: 1
