version: "2"

networks:
  test:

services:
  caliper:
    container_name: caliper
    image: hyperledger/caliper:0.3.0
    command: launch master
    environment:
      - CALIPER_BIND_SUT=fabric:1.4.4
      - CALIPER_BENCHCONFIG=cal-config/config.yaml
      - CALIPER_NETWORKCONFIG=config/network-config.yaml
    volumes:
      - $PWD:/hyperledger/caliper/workspace
    network_mode: host
