version: '2'
volumes:
  couchdb0.org5.ceadar.org_data:
  couchdb0.org5.ceadar.org_etc:
  peer0.org5.ceadar.org_data:
  peer0.org5.ceadar.org_msp:

networks:
  fabric144:
services:
  peer0.org5.ceadar.org:
    container_name: peer0.org5.ceadar.org
    image: hyperledger/fabric-peer
    environment:
     - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_fabric144
     - CORE_PEER_ADDRESS=peer0.org5.ceadar.org:15051
     - CORE_PEER_ID=peer0.org5.ceadar.org
     - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org5.ceadar.org:15051
     - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
     - FABRIC_LOGGING_SPEC=INFO
     - CORE_PEER_GOSSIP_USELEADERELECTION=false
     - CORE_PEER_GOSSIP_STATE_ENABLED=false
     - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
     - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.org5.ceadar.org:5984
     - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
     - CORE_PEER_PROFILE_ENABLED=true
     - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/keystore/key.pem
     - CORE_PEER_GOSSIP_ORGLEADER=true
     - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/tlscacerts/tlsca-cert.pem
     - CORE_PEER_LISTENADDRESS=0.0.0.0:15051
     - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:15151
     - CORE_PEER_LOCALMSPID=Org5MSP
     - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org5.ceadar.org:15051
     - CORE_PEER_CHAINCODEADDRESS=peer0.org5.ceadar.org:15151
     - CORE_PEER_TLS_ENABLED=true
     - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/signcerts/cert.pem
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
     - /var/run:/host/var/run
     - ./../crypto/org5/msp-peer0:/etc/hyperledger/fabric/msp
     - ./../crypto/org5/msp-tls-peer0:/etc/hyperledger/fabric/tls
     - peer0.org5.ceadar.org_msp:/etc/hyperledger/fabric
     - peer0.org5.ceadar.org_data:/var/hyperledger/production
    ports:
     - 15051:15051
    networks:
     - fabric144
  couchdb0.org5.ceadar.org:
    container_name: couchdb0.org5.ceadar.org
    image: hyperledger/fabric-couchdb
    environment:
     - COUCHDB_USER=
     - COUCHDB_PASSWORD=
    volumes:
     - couchdb0.org5.ceadar.org_data:/opt/couchdb/data
     - couchdb0.org5.ceadar.org_etc:/opt/couchdb/etc/local.d
    ports:
     - 16051:5984
    networks:
     - fabric144
